### ISSUE TITLE
Add benchmarking

### ISSUE THREAD

**Issue by mateoatr** [dotnet/linker#1013]
Seeing issues like #918 and knowing how critical the linker results are both time-wise and size-wise, it's my opinion that it'd be beneficial to add a simple benchmarking tool (maybe using [BenchmarkDotNet](https://benchmarkdotnet.org/)?) so that linker contributors can easily see if changes they introduced impact any specific scenario in terms of the time needed to link or the size of the output.

**Comment by vitek-karas** [comment]
@jtschuster started the work to determine how/where/what with regard to perf testing. If we already have a tracking issue for that work, please feel free to close this one. Otherwise we should update the issue with the known plan of things to tackle.
