### ISSUE TITLE
User-friendly warnings when `dynamic` keyword is used

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/linker#1156]
The `dynamic` contextual keyword in C# is not friendly for trimming. The .NET Native analyzer tried to analyze this and a lot of things worked, but it's a non-trivial chunk of work with questionable benefit.

The problem with `dynamic` keyword is best illustrated with this:

```csharp
class Program
{
    static void Main()
    {
        string hello = "Hello";
        dynamic s;
        
        {
            s = "ello";
            hello.IndexOf(s);
        }

        {
            s = 'H';
            hello.IndexOf(s);
        }
    }   
}
```

The above compiles down to:

```csharp
private static void Main()
{
	string hello = "Hello";
	object s2 = "ello";
	if (<>o__0.<>p__0 == null)
	{
		<>o__0.<>p__0 = CallSite<Action<CallSite, string, object>>.Create(Binder.InvokeMember(CSharpBinderFlags.ResultDiscarded, "IndexOf", null, typeof(Program), new CSharpArgumentInfo[2]
		{
			CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.UseCompileTimeType, null),
			CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null)
		}));
	}
	<>o__0.<>p__0.Target(<>o__0.<>p__0, hello, s2);
	s2 = 'H';
	if (<>o__0.<>p__1 == null)
	{
		<>o__0.<>p__1 = CallSite<Action<CallSite, string, object>>.Create(Binder.InvokeMember(CSharpBinderFlags.ResultDiscarded, "IndexOf", null, typeof(Program), new CSharpArgumentInfo[2]
		{
			CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.UseCompileTimeType, null),
			CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null)
		}));
	}
	<>o__0.<>p__1.Target(<>o__0.<>p__1, hello, s2);
}
```

Notice the callsite to `IndexOf` is late-bound (there's no static reference to the method). If one passes something typed as `dynamic` to a framework method, we currently don't have anything guaranteeing the framework method to be kept.

We should ideally have a friendly warning that says "no `dynamic` please". Maybe the `RequiresUnreferencedCodeAttribute` can accomplish that (which would make this a Runtime repo issue). I haven't thought about this much (and I know little about how `dynamic` compiles anyway), so parking the issue here for now.

**Comment by marek-safar** [comment]
Are you suggesting this has to be done on linker side? I thought we'd just annotate https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs method with linker incompatible/unsafe attribute.

**Comment by MichalStrehovsky** [comment]
I think the last part of the issue description answers your question: "Maybe the `RequiresUnreferencedCodeAttribute` can accomplish that (which would make this a Runtime repo issue). I haven't thought about this much (and I know little about how `dynamic` compiles anyway), so parking the issue here for now."

**Comment by vitek-karas** [comment]
I think this has been addressed in the RUC messages and with analyzer which reacts to dynamic invocations.
The above sample now produces these warnings:

From analyzer:
```Console
Program.cs(9,13): warning IL2026: Invoking members on dynamic types is not trimming-compatible. Types or members might have been removed by the trimmer.
Program.cs(14,13): warning IL2026: Invoking members on dynamic types is not trimming-compatible. Types or members might have been removed by the trimmer.
```

From trimmer:
```Console
Program.cs(9,13): Trim analysis warning IL2026: Program.<Main>$(String[]): Using member 'Micro
soft.CSharp.RuntimeBinder.Binder.InvokeMember(CSharpBinderFlags, String, IEnumerable<Type>, Type, IEnumerable<CSharpArg
umentInfo>)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Usin
g dynamic types might cause types or members to be removed by trimmer.
Program.cs(14,13): Trim analysis warning IL2026: Program.<Main>$(String[]): Using member 'Micr
osoft.CSharp.RuntimeBinder.Binder.InvokeMember(CSharpBinderFlags, String, IEnumerable<Type>, Type, IEnumerable<CSharpAr
gumentInfo>)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Usi
ng dynamic types might cause types or members to be removed by trimmer.
```
