### ISSUE TITLE
Improve member signatures used in warnings and errors

### ISSUE THREAD

**Issue by marek-safar** [dotnet/linker#1220]
Most of the code uses `FullName` property to report the name of the member involved in the warning/error message. This is not a great user experience as FullName is very verbose as it includes

- return type
- field type
- property/event type
- modreq/modopt modifiers with their types
- a fully qualified name for primitive types

It also uses a syntax which is not very friendly to high-level language users
- nested types separated by `/`
- .ctor() for constructors
- set_X, get_X for accessors
- `X for generic arity
- etc

I think we should simplify that to make it more friendly to developers writing code in their language. We could start with C# for now and add other languages later.

Perhaps the best way to implement this would be inside Cecil.

**Comment by vitek-karas** [comment]
This is basically fixed, we use "DisplayName" which currently tries to match C# formatting rules. There's a discussion about using Reflection formatting rules, but that's separate from this issue.
