### ISSUE TITLE
Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'ExistingLibraryBuildInFramework4.7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	

### ISSUE THREAD

**Issue by neelesh-infogain** [dotnet/linker#1263]
**Issue Title**

I am getting below errors in IL Linker while trying to publish/compile my Blazor client application in release mode.

1. Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'ExistingLibraryBuildIn.NetFramework4.7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
2. ILLink failed with exit code -532462766. C:\..\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-rc1.20223.4\targets\Blazor.MonoRuntime.targets

I do not get this error while running/publishing in debug mode. 

![image](https://user-images.githubusercontent.com/62283267/84300357-cf8c0100-ab6f-11ea-8512-f36e6bd078e6.png)

**Comment by maisak** [comment]
Having same issue but with other assembly: 
```
Fatal error in Mono IL Linker
3>C:\Users\antho\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0\targets\Blazor.MonoRuntime.targets(326,5): error : Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Interactive.Async, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
3> ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Interactive.Async, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
```

**Comment by marek-safar** [comment]
Could you please try with .NET5 RTM?

**Comment by vitek-karas** [comment]
There has been no reply to this in 2 years, closing. If you're still having issues please reopen or create a new issue.
