### ISSUE TITLE
Provide option to specify which assemblies to emit linker warnings for

### ISSUE THREAD

**Issue by layomia** [dotnet/linker#1348]
We should provide an option for the linker to emit warnings when linking only certain assemblies.

While working on https://github.com/dotnet/runtime/pull/39133, I needed a way to specify that warnings should only be emitted for src assemblies, but there wasn't a good one. The reason in this case was to prevent `IL2047` (https://github.com/mono/linker/pull/1315) from being emitted for ref assemblies. We don't want to add suppression files for ref assemblies, so my workaround was to use the `--nowarn` option and globally suppress for both src and ref assemblies:

https://github.com/dotnet/runtime/blob/c868f2505710438c529abd23ad87337a0d3409fc/eng/illink.targets#L197-L201

cc @mateoatr, @eerhardt, @vitek-karas, @marek-safar

**Comment by vitek-karas** [comment]
This has been basically replaced by the single-warn functionality, where assemblies which don't have source code information will by default only report a single warning. This can also be requested explicitly on the command line.
