### ISSUE TITLE
Show usage message when no arguments are given

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#1353]
When running `illink.dll` without any arguments, it prints "No parameters specified". When given an unrecognized argument, it prints "Unrecognized command-line option: \<option\>".

Should we consider printing more info to make it easier to discover the correct usage? https://github.com/mono/linker/pull/1320 will print the usage message for `-h` and `--help` (in addition to existing `-?`, and `-help`), so it is more discoverable than it used to be.

Pros and cons:
- Printing usage when no arguments are passed gives a lot of output that might be unexpected. It could make the actual error (missing parameters) hard to spot.
- Just printing "No parameters specified" doesn't say how to get more info about the supported arguments.

**Comment by sbomer** [comment]
If we do print some extra information, we should ensure that the message is split into two parts:
- The actual error, surfaced in MSBuild (see https://github.com/mono/linker/issues/1354)
- The usage text, which can have low importance for MSBuild, since the message will likely only apply to command-line scenarios.

**Comment by tlakollo** [comment]
Why not print "No parameters specified. Use -h, --help, -help, -? to see the usage information."

**Comment by sbomer** [comment]
That would work nicely for the command-line - I think just mentioning '--help' should be enough. For the MSBuild message, I think we should just include the actual error. I would expect something like:
```
[ILLink error ILXXXX: No parameters specified.]
Use --help to see the usage information.
```
where the second line isn't surfaced with the error itself.
