### ISSUE TITLE
Define the trim analysis warning category

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#1367]
We need to define which warnings belong in the trim analysis category, since there will be a user-facing flag to turn these on and off. These warnings should be the set that a developer would conceptually associate with trim analysis, and they will be turned off by default in .NET5. For now, the list is planned to live in the SDK, but in future versions it may live in the linker itself. This issue is just about defining what belongs in this category, even if we only use it for documentation.

Currently, that set as defined in the linker codebase (https://github.com/mono/linker/search?q=TrimAnalysis&unscoped_q=TrimAnalysis) is:
- `IL2006` (unrecognized reflection)
- `IL2026` (`RequiresUnreferencedCodeAttribute`)
- `IL2043` (propagating `DynamicallyAccessedMemberAttribute` from property to method which already has it).

I think `IL2006` and `IL2026` clearly belong in the category. Should all of the warnings related to `DynamicallyAccessedMemberTypes` and `RequiresUnreferencedCode` be in it too? That would include:
- `IL2041` about that attribute on a member
- `IL2042` about a property without unique backing field
- `IL2043` about propagating it from a property to a method that already has it
- `IL2046`/`IL2047` about mismatched attributes on virtual methods

The warnings about `DynamicDependencyAttribute` also are conceptually related (`IL2033-IL2037`), and seem like a good candidate for inclusion in the category.

There are also a number of warnings related to removal of unused code - invalid substitution files, for example. Do we consider substitutions and removal of unused branches to be a part of the trimming capability? Or do we envision a way to use substitutions without otherwise trimming unreferenced members?  Attribute removal warnings like `IL2045` (when there's a reference to a removed attribute) are similar.

@vitek-karas @mateoatr @agocke

**Comment by vitek-karas** [comment]
This has already been done - we have https://github.com/dotnet/linker/blob/main/src/ILLink.Shared/DiagnosticCategory.cs and this is surfaced to the user via several different options.
