### ISSUE TITLE
Infer diagnostic severity using the message's code

### ISSUE THREAD

**Issue by mateoatr** [dotnet/linker#1406]
See [comment](https://github.com/mono/linker/pull/1372#discussion_r463761346). Since we use specific code ranges for the different severity levels that we use when logging linker warnings/errors, we should be able to infer the severity of the message being logged by looking at its code (if any) instead of specifying it in the call site by using `LogError`/`LogWarning`.

**Comment by marek-safar** [comment]
What would be the benefit of doing that? I think it's useful to see in the code if the code path leads to error or warning. On top of that, we'd need to pass redundant arguments as these code paths usually have different content requirements.

**Comment by vitek-karas** [comment]
This is now actually enforced in the code. For example calling `MessageContainer.CreateErrorMessage("text", "2010")` will throw since only 1xxx is the error range.
