### ISSUE TITLE
AssemblyName.xml descriptors are not processed from copyused assemblies

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#1410]
https://github.com/dotnet/runtime/issues/40336 mentions warnings generated by invalid XML files in System.PrivateCoreLib. Such warnings show up with `<TrimMode>link</TrimMode>` but not `<TrimMode>copyused</TrimMode>`. The difference is due to the check
https://github.com/mono/linker/blob/8f32ed57a05eeb0bae3790c4db75b316c3da76c7/src/linker/Linker.Steps/BlacklistStep.cs#L126
which prevents processing of XMLs for `copyused` assemblies - hiding the invalid XML (which was pointing to COM members only present on Windows, for example).

I think the XML files should be processed on-demand (similar to https://github.com/mono/linker/issues/1164) only when an assembly is marked.

**Comment by marek-safar** [comment]
I don't think we can process them on demand. Most XML formats allow specifying any assembly in their XML so we need to read them and process them. It'd also complicate the scenario when doing on-demand processing we need to load a new assembly and process it again.

I think that switch is missing `copyused` value.

**Comment by sbomer** [comment]
@marek-safar Could we get rid of the support for `AssemblyName.xml` entirely? The recommendation recently has been to call it `ILLink.Descriptors.xml`. If it helps, we could warn if the linker discovers an `AssemblyName.xml` to make sure it doesn't bite people.

**Comment by marek-safar** [comment]
I think we'd need to phase it. This has been the original way to add descriptors and there is a decent chance that some of Xamarin libs will use it. We should add a warning first.

**Comment by sbomer** [comment]
Copying @mateoatr's [comment](https://github.com/dotnet/runtime/pull/48430#issuecomment-781724694):

>> Does anyone else other than dotnet/runtime use the AssemblyName.xml for descriptors?
>
> Looks like dotnet/wpf uses it too: https://github.com/dotnet/wpf/blob/78be6d01ca468a6d137af0681859890544210987/src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj#L1470-L1474

**Comment by vitek-karas** [comment]
@sbomer - given that we now process descriptors on demand (effectively) can this be fixed? That is should we add `CopyUsed` to the switch here: https://github.com/mono/linker/blob/4f68312aeb4b8b906bee4e06438020ad6721c522/src/linker/Linker/EmbeddedXmlInfo.cs#L116-L124

**Comment by sbomer** [comment]
We could, but I'm not sure it's worth it. I'm slightly worried that it could somehow regress .NET5 scenarios either in terms of size or by activating latent XML errors. Probably rare, but possible. This issue only exists for the combination of `copyused` and `AssemblyName.xml`, both of which are not recommended.

If we do fix it we should do a sanity check by publishing a .NET5  or .netcoreapp3 WPF app. What do you think?

**Comment by vitek-karas** [comment]
If you think this should be very rare I would probably be OK taking the change.
That said my intent was to resolve this issue - one way or another. We could also choose to not fix this and turn that into a "feature".

**Comment by vitek-karas** [comment]
Let's "not fix this", we haven't run into this for more than a year, so it's not a problem.
