### ISSUE TITLE
MonoLinker.exe should embed the .pdb and use SourceLink

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/linker#1427]
I was debugging into MonoLinker.exe and it didn't have symbols so it was a bit painful. 

Would be nice to:
1. set `<DebugType>embedded</DebugType>`
2. add a `<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" />`
3. set `<EmbedUntrackedSources>true</EmbedUntrackedSources>` to include generated files

for easier debugging experience

**Comment by vitek-karas** [comment]
We're shipping linker the same way other tools in the .NET ecosystem are shipped - we're now using Arcade and all of that.
