### ISSUE TITLE
Define readable warning names

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#1432]
We should come up with short readable names for the warnings. From https://github.com/dotnet/runtime/pull/40865#discussion_r470904863:

> do we have a better string than UnrecognizedReflectionPattern now? It sort of made sense when IL2006 was used, but now we are using 30 differnet codes, all with "UnrecognizedReflectionPattern"

These can be used to make `UnconditionalSuppressMessage` more readable, for example:
```csharp
[UnconditionalSuppressMessage("ReflectionAnalysis", "IL2070:UnmetDynamicRequirements", "reason")]
```

**Comment by sbomer** [comment]
A related question is whether the linker should enforce that the correct string is given for a warning code - currently there can be an arbitrary string after the warning code.

**Comment by vitek-karas** [comment]
We do define short names: https://github.com/dotnet/linker/blob/main/src/ILLink.Shared/DiagnosticId.cs
Not sure if we want to do this more "publicly".

The idea of validating these is now basically impossible to implement. We've shipped without validation, and so there is unknown number of supressions out there which don't have the right text. We can't break those. This includes our own runtime: 
https://github.com/dotnet/runtime/blob/6a889d234267a4c96ed21d0e1660dce787d78a38/src/libraries/System.Data.Common/src/System/Data/Common/DbConnectionStringBuilder.cs#L15-L17
