### ISSUE TITLE
Some trim analysis warnings are duplicated

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/linker#1483]
Linker has intrinsics handling for some of reflection APIs which produce the same warnings as annotating the APIs does. At the same time, there's no logic to avoid reporting the same warning twice because of this.

For example, code like this:
```C#
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            CreateItTest<string>();
        }

        static object CreateItTest<T>()
        {
            return Activator.CreateInstance<T>();
        }
```

Produces two identical warnings: 
```console
F:\ILLinker\repro\ACIT\Program.cs(14,9): Trim analysis warning IL2091: ACIT.Program.CreateItTest<T>(): The requirements declared via the 'DynamicallyAccessedMembersAttribute' on the generic parameter 'T' of 'ACIT.Program.CreateItTest<T>()' don't match those on the generic parameter 'T' of 'System.Activator.CreateInstance<T>()'. The source value must declare at least the same requirements as those declared on the target location it's assigned to [F:\ILLinker\repro\ACIT\ACIT.csproj]
F:\ILLinker\repro\ACIT\Program.cs(15,13): Trim analysis warning IL2091: ACIT.Program.CreateItTest<T>(): The requirements declared via the 'DynamicallyAccessedMembersAttribute' on the generic parameter 'T' of 'ACIT.Program.CreateItTest<T>()' don't match those on the generic parameter 'T' of 'System.Activator.CreateInstance<T>()'. The source value must declare at least the same requirements as those declared on the target location it's assigned to [F:\ILLinker\repro\ACIT\ACIT.csproj]
```

One (the first one) comes from the annotations, the other comes from intrinsic handling.

We should either remove intrinsic handling for cases which are fully covered by annotations, or add logic to avoid duplicate warnings like these.

**Comment by marek-safar** [comment]
Should not we ignore the hardcoded logic when any annotation exist? In the worst case, we could actually end up with 2 conflicting warnings for some code construct when they go out of sync?

**Comment by vitek-karas** [comment]
We probably should, but not always - it's a tricky thing.
For example Type.GetMethod - if we turn off intrinsic handling it will work, but for case like:
```C#
typeof(Foo).GetMethod("Method1");
```

Intrinsic handling will mark only Foo.Method1. Annotation based handling will mark all public methods on Foo.

So in short, this needs "more work" - maybe even case-by-case handling.

The CreateInstance<T> is a simple case - there we should disable intrinsic handling.
