### ISSUE TITLE
Consider warning is ILLink task detects C++/CLI assemblies

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/linker#1540]
Currently ILLink task detects C++/CLI assemblies and removes them from the list passed to the linker (since linker can't handle these). Assuming the removal actually works (see https://github.com/mono/linker/issues/1539 for details of when that's not true), this effectively creates a hole in linker analysis. Linker doesn't see the entire application anymore and thus trimming may remove things which are necessary to successfully run the C++/CLI assemblies.

As such ILLink task should probably warn if this happens.

Going forward we may want to consider adding another action to the linker - something like "analyze but don't touch" - C++/CLI assemblies would be passed to the linker, but with this special action. Linker would be allowed to run analysis on them (to fill in the holes), but it would not be allowed to modify them in any way - so for example even facade elimination would not be allowed.

**Comment by marek-safar** [comment]
I think we should hand this inside linker as "temporary" step where we switch from link to copy mode for such assemblies with a warning.

**Comment by vitek-karas** [comment]
If we let linker analyze the assembly, then no warning should be necessary - but it would require us to correctly handle facades.

**Comment by vitek-karas** [comment]
Linker now allows only `skip` or `copy` actions on C++/CLI assemblies. If no action is explicitly specified for a given assembly it will default to `copy`. So C++/CLI assemblies are analyzed, but they're left unchanged in the output.
