### ISSUE TITLE
Improve crash dump creation/logging for illink.exe

### ISSUE THREAD

**Issue by agocke** [dotnet/linker#1592]
Currently exceptions are caught and swallowed in illink, which means that no crash dumps are automatically created.

We may want to follow the csc model here: when an exception is thrown, write a message and stack to the console, but then let the exception flow unhandled out of the app. Exception filters can be used here to prevent destroying the dump, which otherwise would lose the local variable info in the reported crash dump.

**Comment by vitek-karas** [comment]
This has been fixed in https://github.com/dotnet/linker/pull/2825 - unhandled exceptions are now left untouched and will throw outside of Main.
