### ISSUE TITLE
Make Linker analyzer's documentation more friendly to .NET Core SDK users.

### ISSUE THREAD

**Issue by layomia** [dotnet/linker#1676]
Following up from https://github.com/mono/linker/pull/1668, we should consider making the Linker analyzer's README and any related docs more friendly to .NET Core SDK users.

One specific issue is that the `LinkerDumpDependencies` property mentioned in the doc does not work on the .NET Core SDK, but `_TrimmerDumpDependencies` does (and is not documented).

**Comment by vitek-karas** [comment]
The readme in this repo now correctly documents both options. The only public docs about LinkerDumpDependencies are odl Xamarin mentions. We intentionally don't document the new property for .NET Core linker as we don't think it's ready for public consumption yet (and more importantly we don't want to sign up for not breaking it in the future).
