### ISSUE TITLE
DisablePrivateReflectionAttribute should not be added to delegate target methods

### ISSUE THREAD

**Issue by vargaz** [dotnet/linker#1682]
The System.Runtime.CompilerServices.DisablePrivateReflectionAttribute attribute is used by the AOT compiler to determine whenever a private method has any indirect callers, if not, the method can participate in interprocedural optimizations. The linker should not add this attribute to methods which are targets of delegates, i.e.:
```
using System;
public class HelloWorld
{
	static void Foo () {
	}

	public static void Main (String[] args) {
		var a = new Action (Foo);
	}
}
```
Expected result: After linking, the  'Foo' method shouldn't have this attribute.

The fix is to call MarkIndirectlyCalledMethod () in MarkStep.cs for  OperandType.InlineMethod+Ldftn/Ldvirtftn.

**Comment by vitek-karas** [comment]
Currently this is turned off by default in the linker. @vargaz  Does Xamarin enable this explicitly? 

That said - the bug is correct and it should be fixed.

**Comment by vargaz** [comment]
This is not currently used by the AOT compiler, so its low priority.

**Comment by vargaz** [comment]
This seems to be fixed now.
