### ISSUE TITLE
Add IL verifier to illink tests

### ISSUE THREAD

**Issue by marek-safar** [dotnet/linker#1703]
We are running with no IL and metadata verification for linker tests on netcore builds. We have only [support for perify](https://github.com/mono/linker/blob/master/test/Mono.Linker.Tests/TestCasesRunner/PeVerifier.cs) which is .NET framework tool and we need to port the support to use .NET Core verifier.

This is increasingly important as we run more tests on netcore configuration only and our tests don't have another way to verify the output metatada and IL are correct.

The tool we could use is https://github.com/dotnet/runtime/tree/10381a2cdc33860f0dc649b24cbb703d23b9ea33/src/coreclr/tools/ILVerify

**Comment by vitek-karas** [comment]
This was implemented in https://github.com/dotnet/linker/pull/2960
