### ISSUE TITLE
Document trimmer warnings

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/linker#1748]
Analyzers shipped with the .NET SDK should be doc'ed in dotnet/docs repository.

@gewarren FYI

**Comment by sbomer** [comment]
@agocke fixed this in https://github.com/dotnet/docs/pull/25324, and @mateoatr documented a bunch more in https://github.com/dotnet/docs/pull/25842. Somebody needs to pick up https://github.com/dotnet/docs/pull/26413 to get the rest of them.

**Comment by gewarren** [comment]
Can this be closed now that dotnet/docs#26413 is merged?
