### ISSUE TITLE
Where to warn on dynamically accessed types with derived members annotated with RequiresUnreferencedCode

### ISSUE THREAD

**Issue by mateoatr** [dotnet/linker#1797]
Dynamically accessed types that derive from types which have any of its members annotated with the `RequiresUnreferencedCode` attribute currently cause the linker to produce a warning (IL2026) that points to the member on the base type:

```C#
// a.cs
class Bar
{
    [RequiresUnreferencedCode ("Warn from Bar")]
    public void Method() { }
}

class Foo : Bar
{
    // Note that we are obliged to annotate this method with RUC,
    // otherwise we will produce (IL2027).
    [RequiresUnreferencedCode ("Warn from Foo")]
    public void Method() { }
}
```

```C#
// b.cs
class MyClass
{
    void MyMethod()
    {
           KeepAllPublicMethodsOnType(typeof(Foo));
    }
    
    static void KeepAllPublicMethodsOnType(
        [DynamicallyAccessedMembers (DynamicallyAccessedMemberTypes.PublicMethods)] Type type)
    {
    }
}
```

This will produce a warning similar to: `ILLink: Trim analysis warning IL2026: MyClass.MyMethod(): 'Bar.Method()' method has 'RequiresUnreferencedCodeAttribute' which can break functionality when trimming application code. Warn from Bar.` Although correct, from the standpoint of the user, which is dynamically accessing `Foo`, this might be seen as an odd message. The question here is if we should blame the deriving type in this scenario or keep the current behavior.

**Comment by MichalStrehovsky** [comment]
For the "Note that we are obliged to annotate this method" part - is the warning produced even though the method is not virtual? That would be a bug. Bar.Method and Foo.Method are unrelated. They have the same name, but we would never end up in a situation where illink doesn't know unambiguously which one we are calling. (For virtual methods it can't tell.)

**Comment by vitek-karas** [comment]
For virtual methods (non-virtuals should not have this problem as per @MichalStrehovsky comment) I think it's just a nice to have. It would be nice to point to the more derived overload if we can, but it's not that important. For one it's a relatively niche case and then it very possible to get warning on the base type for methods which don't have derived type overloads.
