### ISSUE TITLE
Remove DefaultDllImportSearchPathsAttribute automatically

### ISSUE THREAD

**Issue by marek-safar** [dotnet/linker#1872]
Always remove assembly-level DefaultDllImportSearchPathsAttribute when there are no p-invokes left after sweep-step.

**Comment by MichalStrehovsky** [comment]
AFAIK this attribute would be also used if the assembly in question is passed as a parameter to [NativeLibrary.TryLoad](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.tryload?view=net-5.0#System_Runtime_InteropServices_NativeLibrary_TryLoad_System_String_System_Reflection_Assembly_System_Nullable_System_Runtime_InteropServices_DllImportSearchPath__System_IntPtr__) and search path is not specified (it's a nullable).

**Comment by vitek-karas** [comment]
I don't see much value in doing this - it could have additional potential breaking impact (see @MichalStrehovsky comment) and the size saving seem rather small (at best one attribute instance per assembly).
