### ISSUE TITLE
Remove special handling of TypeDescriptionProviderAttribute and TypeConverterAttribute

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/linker#1942]
`TypeDescriptionProviderAttribute` - the `.ctor` parameter are now annotated with `PublicParameterlessConstructor` and so the intrinsic handling in linker is not necessary anymore (linker would preserve any parameterless .ctor on the type).

`TypeConverterAttribute` - the `.ctor` parameter is annotated with `PublicConstructors`
* Linker will mark any parameterless constructor on the type intrinsically
* Linker will also mark any method which has exactly one parameter with type `System.Type`. Since the type must be `TypeConverter` derived, that means methods `CanConvertFrom` and `CanConvertTo`.

The `.ctor` part is covered by the annotation. It's unclear why linker preserves the other methods though.

**Comment by vitek-karas** [comment]
@marek-safar the original logic was added by you in https://github.com/mono/linker/pull/778/files - do you remember why linker preserves any method with `Type` parameter on the target type?

@eerhardt since you did the annotation work on this - any idea why preserving methods with `Type` parameter would help? Is it needed (I assume not since the annotations would otherwise specify `PublicMethods` or something similar).

**Comment by marek-safar** [comment]
> do you remember why linker preserves any method with Type parameter on the target type?

This looks like a bug. It should apply to constructors only.

**Comment by marek-safar** [comment]
I linked this with existing #1349

**Comment by eerhardt** [comment]
The System.ComponentModel.TypeConverter assembly is now fully annotated (sans one remaining warning about MaskedTextProvider which is not relevant here). None of the usages of the `TypeDescriptionProviderAttribute` needs PublicMethods.

https://github.com/dotnet/runtime/blob/52f986706dc96b4b146c6657e6bcce1f5d29cc55/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L333-L339

Looking at the usages of `TypeConverterAttribute`, there are also some usages from WindowsBase and System.Xaml, and some other assemblies in full framework:

https://referencesource.microsoft.com/#System/compmod/system/componentmodel/TypeConverterAttribute.cs,70f7fb9a74c8db1f,references

* System.Activities.Presentation
* System.Configuration
* System.ServiceModel.Web
* System.Web
* System.Web.DataVisualization
* etc

Honestly, I can't think of any reason why that rule was added for TypeConverters.

**Comment by eerhardt** [comment]
Looking at the PR, I wonder if it was meant to handle this case:

https://github.com/mono/linker/pull/778/files#diff-85d907c0a93cce04b7e233874d9157a03e5950b94d565b90c3f2f3a136c85a3eR20-R22

```C#
		class Custom1 : TypeConverter
		{
			[Kept]			
			public Custom1 (Type type)
			{
			}
```

The case where the constructor took a single `Type` argument.

**Comment by eerhardt** [comment]
Note: I hit this issue in a `dotnet new maui` app today. The issue manifested itself in a strange way:

```
ILLink : Trim analysis warning IL2111: Microsoft.Maui.Controls.IVisual: Method 'Microsoft.Maui.Controls.VisualTypeConverter.CreateVisual(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [C:\DotNetTest\MauiTest\MauiTest.csproj]
```

```C#
	[System.ComponentModel.TypeConverter(typeof(VisualTypeConverter))]
	public interface IVisual
	{
	}

	public class VisualTypeConverter : TypeConverter
	{
		static IVisual CreateVisual(
			[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] Type visualType)
		{
...
```

We have that code in Maui. Since there is a method with a single parameter of type `System.Type`, this rule is firing:

https://github.com/dotnet/linker/blob/7079b345d248c3d76de27ff652ed9fa3d7315bf6/src/linker/Linker.Steps/MarkStep.cs#L2057-L2063

Since this method is a private static method, that is never used in Reflection, this is a bogus warning.

As above, we have annotated TypeConverterAttribute correctly with DynamicallyAccessedMembers. So the TypeConverter constructors will be preserved that way. We should be able to just delete all this special TypeConverter handling code in the linker.

**Comment by vitek-karas** [comment]
I think the agreement is that we should remove special handling of these types in the linker because the annotations already cover everything the runtime needs about them - which is also proved by the fact that the linker analysis of the callsites is clean.

The risk of breaking anything with this should be very low - and if it does break something, I'd like to know, because that would point to a bug in the analysis on the consumption side.

**Comment by eerhardt** [comment]
Re-opening to consider backporting this to .NET 6 for Maui.

I'm seeing the following warnings 330 times when trimming a Maui app, which is causing A LOT of noise.

```
ILLink : Trim analysis warning IL2111: Microsoft.Maui.Controls.VisualElement.Visual: Method 'Microsoft.Maui.Controls.VisualTypeConverter.CreateVisual(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
ILLink : Trim analysis warning IL2111: Microsoft.Maui.Controls.VisualElement.Visual: Method 'Microsoft.Maui.Controls.VisualTypeConverter.CreateVisual(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
ILLink : Trim analysis warning IL2111: Microsoft.Maui.Controls.VisualElement.Visual: Method 'Microsoft.Maui.Controls.VisualTypeConverter.CreateVisual(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
ILLink : Trim analysis warning IL2111: Microsoft.Maui.Controls.VisualElement.Visual: Method 'Microsoft.Maui.Controls.VisualTypeConverter.CreateVisual(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
ILLink : Trim analysis warning IL2111: Microsoft.Maui.Controls.VisualElement.Visual: Method 'Microsoft.Maui.Controls.VisualTypeConverter.CreateVisual(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
ILLink : Trim analysis warning IL2111: Microsoft.Maui.Controls.VisualElement.Visual: Method 'Microsoft.Maui.Controls.VisualTypeConverter.CreateVisual(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
ILLink : Trim analysis warning IL2111: Microsoft.Maui.Controls.VisualElement.Visual: Method 'Microsoft.Maui.Controls.VisualTypeConverter.CreateVisual(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
```

cc @agocke

**Comment by sbomer** [comment]
Closing again since this was backported in https://github.com/dotnet/linker/pull/2695
