### ISSUE TITLE
Add support for abstract static interface members

### ISSUE THREAD

**Issue by agocke** [dotnet/linker#2058]
The linker shouldn't trim the interface definition when trimming in library mode, and we likely need to support the same implementation checks that we do for other interface members.

The minimum bar for .NET 6 is to ensure that runtime libraries are trim safe with this feature. The following check list tracks the tasks that are needed for the full support of this feature

- [x] Trimmer support for the IL changes. Specifically, the trimmer matches the runtime [changes](https://github.com/dotnet/runtime/pull/52173).

> - [x] The runtime tests can be found [here](https://github.com/dotnet/runtime/tree/main/src/tests/Loader/classloader/StaticVirtualMethods) which contains tests in IL for `TypeHierarchy`, `GenericContext`, `InterfaceVariance`, and negative tests.

- [x] Add C# tests to the trimmer that tests this feature comprehensively (will require an updated compiler with the static interface support enabled)
- [x] Reflection support, specifically `MakeGenericType `and `MakeGenericMethod`.
- [x] Trimmer annotations are correctly propagated.
  - [x] Validate DAM on type implementing static interface, or on interface type itself keeps interface members
  - [x] Validate DAM on generic in interface method signature, or on interface type gets applied
  - [x] Validate matching of DAM/RUC on interface method and implementing overrides
- ~~[ ] https://github.com/dotnet/linker/issues/2733 - potential improvement as this could reduce size~~

**Comment by agocke** [comment]
@LakshanF Has anything been finished here?

**Comment by LakshanF** [comment]
The IL support

**Comment by agocke** [comment]
+ @jtschuster who was looking at some of these problems. Looks like runtime is still hitting issues -- we should probably try to run the linker against https://github.com/dotnet/runtime/pull/68612 directly and see if we can find and solve the problem

**Comment by jtschuster** [comment]
I've confirmed that the linker removes all unused `INumber<>` interfaces in a hello world application.
cc @vitek-karas
