### ISSUE TITLE
Support analyzer tests with additional assemblies

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/linker#2107]
Currently it seems that we don't have much coverage for analyzer tests of interactions between multiple assemblies. Specifically for the RUC analyzer, test cases for code which calls RUC annotated methods from different assembly.

Linker has some of these tests in `RequiresUnreferencedCodeCapability` but the analyzer test infra doesn't handle `SetupCompileBefore` and similar attributes, so those cases has to be disabled for analyzer.

**Comment by tlakollo** [comment]
Closed via https://github.com/dotnet/linker/pull/2201
