### ISSUE TITLE
Analyzer allows RUC/RAF in static constructor

### ISSUE THREAD

**Issue by tlakollo** [dotnet/linker#2347]
Trimmer generates warning IL2116 when RUC is placed in a static constructor but analyzer doesn't do anything in those cases, moreover, the behavior for RAF is undefined since it doesn't support RAF on type

**Comment by jtschuster** [comment]
Do you have an example of a piece of code where the trimmer raises the warning? I think this code should generate IL2116 but I'm not getting it when I publish self-contained.

```C#
class Program {
    static int Main() {
        C c = new C();
        int v = C.m();
        Console.WriteLine($"{v}");
        return 0;
    }
}

class C {
    private static int x;
    public C() {  }

    [RequiresUnreferencedCode("asdf")]
    static C() { x = 1; }

    public static int m() { return x; }
}
```
