### ISSUE TITLE
Fail tests in analyzer infra when analyzer throw exceptions

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#2404]
As per the title - we should find a way for the analyzer test infrastructure to fail tests when analyzers throw exceptions.

Currently exceptions in the analyzer seem to allow it to continue analyzing other methods (presumably the exception only aborts analysis of the method which causes it to throw). The exceptions show up as warnings in the UI when consuming an analyzer, and we need to make sure this doesn't happen.

**Comment by sbomer** [comment]
At the moment I'm planning to address this as part of https://github.com/dotnet/linker/issues/2415 since exceptional control flow is causing the analyzer to throw a lot of exceptions.

**Comment by vitek-karas** [comment]
Can we port this to main? I'd be happy to help on that. (There should be much fewer test failures in main since it doesn't have DAM analyzer).

**Comment by sbomer** [comment]
I'll probably push it to @tlakollo's PR which I believe fixes failures that this currently causes in main.

**Comment by tlakollo** [comment]
Fixed in #2400
