### ISSUE TITLE
[DAM Analyzer] Add a basic analyzer test to test the DynamicallyAccessedMembersBinder port

### ISSUE THREAD

**Issue by LakshanF** [dotnet/linker#2410]
Given that @tlakollo has already started to work on adding tests, I'm opening an issue to track [this ](https://github.com/dotnet/linker/pull/2394#pullrequestreview-818381821)comment to add a test case to PR #2394

**Comment by tlakollo** [comment]
Closing via https://github.com/dotnet/linker/pull/2418
