### ISSUE TITLE
Flaky test - Mono.Linker.Tests.GetDisplayNameTests.TestGetDisplayName

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/linker#2451]
Full name of the test: `TestGetDisplayName(MethodWithNestedGenericTypeArguments,DisplayNameAttribute)`

Sometimes it fails with:
```console
Expected string length 203 but was 185. Strings differ at index 182.
Expected: "...[]>.NestedGenericClassMultipleParameters<Char*[],Int32[,][]>)"
But was:  "...[]>.NestedGenericClassMultipleParameters`2)"
------------------------------------------------------^
```

It happened several times to me locally and now I've seen it in CI as well: https://dev.azure.com/dnceng/public/_build/results?buildId=1515259&view=ms.vss-test-web.build-test-results-tab&runId=43119672&resultId=100616&paneView=debug

Locally it always passes on rerun. I suspect test order issue or something similar, but I have no hard data to prove anything.

**Comment by sbomer** [comment]
Fixed by https://github.com/dotnet/linker/pull/2701
