### ISSUE TITLE
DynamicallyAccessedMemberTypes.Interfaces does not cover GetInterfaces on base type

### ISSUE THREAD

**Issue by roji** [dotnet/linker#2473]
The following method causes what seems to be a false positive trim analysis warning:

```c#
static IEnumerable<Type> GetDeclaredInterfaces(
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.Interfaces)] Type type)
{
    var interfaces = type.GetInterfaces();

    if (type.BaseType == typeof(object)
        || type.BaseType == null)
    {
        return interfaces;
    }

    return interfaces.Except(type.BaseType.GetInterfaces());
}
```

The call of GetInterfaces() on type.BaseType triggers:

```
/home/roji/projects/test/Program.cs(22,5): Trim analysis warning IL2075: Program.<<Main>$>g__GetDeclaredInterfaces|0_0(Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.Interfaces' in call to 'System.Type.GetInterfaces()'. The return value of method 'System.Type System.Type::get_BaseType()' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/home/roji/projects/test/Test.csproj]
```

If all interfaces on `type` are preserved, all interfaces on its base type should be preserved as well. There may be a similar issue with other DynamicallyAccessedMemberTypes members as well.

**Comment by vitek-karas** [comment]
Good catch - https://github.com/dotnet/linker/pull/2476 has the fix, we'll try to take it for 6.0.2xx.

**Comment by vitek-karas** [comment]
Fixed by https://github.com/dotnet/linker/pull/2476 for 6.0.2xx.

**Comment by roji** [comment]
@vitek-karas I'm running into this for DynamicallyAccessedMemberTypes.PublicFields - can you confirm that this (and other relevant annotations) are also propagated via BaseType?

**Comment by vitek-karas** [comment]
Almost all public members should be propagated. The code for this is here: https://github.com/dotnet/linker/blob/89ae0f07830215484f1fa7022ab41d66523c9962/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs#L1275-L1298

Private member annotations are not propagated, because that's how reflection works. Meaning calling Type.GetMethods() (with any combination of binding flags) will never return private members on the base type. The annotations were designed to follow the same semantics as reflection binding.

**Comment by roji** [comment]
Perfect, thanks @vitek-karas!

**Comment by vitek-karas** [comment]
Note: Everything but the Interfaces should already work in 6.0... so if you see anything different, please let us know.
