### ISSUE TITLE
GetTypeInfo().GetDeclaredMethod() generates a false positive warning

### ISSUE THREAD

**Issue by roji** [dotnet/linker#2483]
It seems that while the linker properly recognizes `Type.GetMethod()` and `Type.GetTypeInfo().GetMethod()`, it generates a warning when `Type.GetTypeInfo().GetDeclaredMethod()` is used (but the program does work):

```c#
class Program
{
    public static void Main()
    {
        // These works:
        // var openMethod = typeof(Program).GetMethod("Foo")!;
        // var openMethod = typeof(Program).GetTypeInfo().GetMethod(nameof(Foo))!;

        // This works, but generates a warning:
        var openMethod = typeof(Program).GetTypeInfo().GetDeclaredMethod(nameof(Foo))!;

        var method = openMethod.MakeGenericMethod(typeof(string));
        method.Invoke(null, null);
    }

    public static void Foo<T>()
        => Console.WriteLine("Foo" + default(T));
}
```

/cc @vitek-karas

**Comment by vitek-karas** [comment]
What is the warning it generates?

The `GetDeclaredMethod` is annotated like this:
```C#
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)]
public virtual MethodInfo? GetDeclaredMethod(string name) ...
```

Meaning that the "this" passed to it must keep all methods (public and private).

Unlike `Type.GetMethod` trimmer doesn't have a special case for this, so it doesn't matter if the name of the method is statically known or not, the trimmer will simply keep all methods on the target type.

**Comment by roji** [comment]
Sorry for leaving out the details. The problem isn't with GetDeclaredMethod, it's with MakeGenericMethod called on its result:

> /home/roji/projects/test/Program.cs(20,9): Trim analysis warning IL2060: Program.Main(): Call to 'System.Reflection.MethodInfo System.Reflection.MethodInfo::MakeGenericMethod(System.Type[])' can not be statically analyzed. It's not possible to guarantee the availability of requirements of the generic method. [/home/roji/projects/test/Test.csproj]

**Comment by vitek-karas** [comment]
I see - that's the same root cause as I mentioned above that there's no intrinsic handling for `TypeInfo.GetDeclaredMethod` - meaning linker doesn't know which method the `MakeGenericMethod` is called on.

We could add that if necessary... it's just that for now we didn't find the need.

**Comment by roji** [comment]
We have quite a lot of usage of TypeInfo in the code base - I can't say it's super important or anything, mainly that the APIs there are sometimes slightly easier to use. If TypeInfo really is discouraged by now, we can make the switch where necessary...

**Comment by MichalStrehovsky** [comment]
Yeah, it's pretty discouraged: https://github.com/dotnet/runtime/issues/61122

**Comment by roji** [comment]
Thanks @MichalStrehovsky, I'll go ahead and close this, and remove any problematic references to TypeInfo.
