### ISSUE TITLE
[feature/damAnalyzer] Some of the tests wont run

### ISSUE THREAD

**Issue by tlakollo** [dotnet/linker#2545]
Grabbing the latest version of feature/damAnalyzer and running the test in the test explorer will cause no effect. It will display a small amount of running tests but it won't tell you which ones. Running `dotnet test illink.sln` provides the following warning message:

Dependent Assembly testcentric.engine.metadata, Version=1.4.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb of A:\Repos\TestDamAnalyzer\linker\artifacts\bin\Mono.Linker.Tests\Debug\net6.0\Mono.Linker.Tests.dll not found. Can be ignored if not an NUnit project.
No test is available in A:\Repos\TestDamAnalyzer\linker\artifacts\bin\Mono.Linker.Tests\Debug\net6.0\Mono.Linker.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Then it will skip all the Mono.Linker.Tests and only run a small subset of test mostly analyzer stuff. The main branch seems to be working fine.

**Comment by vitek-karas** [comment]
I tried this on my Windows 11 machine:
* fetched the latest feature/damAnalyzer - 43a45240
* git clean
* .\build.cmd
* dotnet test illink.sln

It worked without any issues, ran all the tests as expected. Specifically the linker tests reported:
```console
Passed!  - Failed:     0, Passed:  1007, Skipped:    34, Total:  1041, Duration: 3 m 2 s - Mono.Linker.Tests.dll (net6.0)
```

**Comment by tlakollo** [comment]
Closing I figure out that I always run an alias that builds main, then I checked out feature/damAnalyzer and make an incremental build and leave stuff in a bad state
