### ISSUE TITLE
[DAM analyzer] don't produce warnings for unsupported intrinsics

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#2578]
As per the title - until we implement support for an intrinsic, the DAM analyzer should not produce warnings for calls to the intrinsic (even when annotated with RUC), or for values returned from the intrinsic.

**Comment by tlakollo** [comment]
I open this one for the same purpose https://github.com/dotnet/linker/issues/2559

**Comment by sbomer** [comment]
Thanks, I missed that one when I was looking for an existing issue. Closing as a duplicate.

**Comment by sbomer** [comment]
Actually - I will keep this issue open to track "disabling" the intrinsics (making it so they don't produce warnings, as a precondition for closing out the feature branch), and we can use your issue to track enabling them in the analyzer for feature parity.

**Comment by sbomer** [comment]
Fixed by https://github.com/dotnet/linker/pull/2596 and https://github.com/dotnet/linker/pull/2597
