### ISSUE TITLE
[DAM analyzer] Don't produce dataflow warnings for annotations on invalid types

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#2598]
When `typeof(T).TypeHandle` flows into an unannotated location, the linker and analyzer are both producing warnings about an unknown value failing to meet the DAM requirements. There are two problems here:

- We shouldn't be producing warnings for unknown values when there are no requirements.
- We aren't flowing annotations on `T` through `get_TypeHandle`. I think it would make sense to do this.

I think we should fix it by propagating the annotations from the generic parameter through `get_TypeHandle`.

**Comment by tlakollo** [comment]
Closed via #2599
