### ISSUE TITLE
source-build: Remove Microsoft.CodeAnalysis.BannedApiAnalyzers prebuilt

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/linker#2615]
Building linker in source-build introduces Microsoft.CodeAnalysis.BannedApiAnalyzers as a prebuilt.  Microsoft.CodeAnalysis.BannedApiAnalyzers is not something that is included in source-build.  This prebuilt either needs to be addressed.  Microsoft.CodeAnalysis.BannedApiAnalyzers is typically only utilized in non-source-build legs.

This is currently blocking release/6.0.2xx source-builds so the fix must flow appropriately.

**Comment by MichaelSimons** [comment]
cc @sbomer  - It looks like this may have been caused by https://github.com/dotnet/linker/pull/2234.  It must have flowed into release/6.0.2xx and regressed source-build.

**Comment by sbomer** [comment]
@MichaelSimons what is the ask here? Does BannedApiAnalyzers need to be included in source build? Or would it suffice to make the packagereference to Microsoft.CodeAnalysis.BannedApiAnalyzers conditional so that it can be disabled for source build?

**Comment by sbomer** [comment]
@omajid, it looks like you originally added a source build of this repo. Do you have any guidance here?

**Comment by MichaelSimons** [comment]
Other repos have been making the packagereference conditional for source build.  Here is an example: https://github.com/NuGet/NuGet.Client/blob/dev/build/common.project.props#L287

**Comment by MichaelSimons** [comment]
The fix needs backporting to 6.0
