### ISSUE TITLE
PreserveDependencyAttribute

### ISSUE THREAD

**Issue by SerratedSharp** [dotnet/linker#2657]
This documentation mentions the PreserveDependencyAttribute, but I'm not able to locate this attribute.  I see it discussed in other issues.  Is the attribute still available or does the doc need to be udpated?

**Comment by sbomer** [comment]
It's deprecated, see https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2033. We should probably update our docs, where did you see it mention PreserveDependencyAttribute?
