### ISSUE TITLE
Support PublishTrimmed for non-self-contained applications

### ISSUE THREAD

**Issue by normj** [dotnet/linker#2703]
When turning on trimming for publishing .NET application it requires the application to be published for as a self contained application. My assumption is trimming was meant for distributing stand alone framework independent applications and to have the size be as small as possible for distributing those stand alone applications.

For cases like AWS Lambda and I assume Azure Functions customers are generally publishing their applications as framework dependent. Cold start performance for these types of applications is critical and deployment bundle plays a large factor in cold start performance. It would be great if we could enable trimming but keep `--self-contained` equal to `false`.

A bonus case is AWS Lambda supports both deploying as a class library and as an executable. Class library being the more common of the 2 scenarios. Ideally what we would like is to tell the compiler from this arbitrary method in a class library perform trimming. If that is not possible we can steer users to the executable flow if they want to enable trimming.

**Comment by agocke** [comment]
Could you elaborate a bit? Is the idea that users build fx-dependent apps, and reference some third-party SDK, and that 3rd-party SDK is large enough that trimming is important?

Could we get some basic numbers on this scenario? What size apps are we talking about, what's the size after trimming, what's the startup improvement, etc?

**Comment by normj** [comment]
Yes, users are building a fx-dependent apps. The goal is to have all of the user's application and class libraries as well as third party  assemblies trimmed. Typical size of Lambda and Azure functions is a few megs although there are examples of much large applications. 

The goal is to have .NET run well in constraint CPU/Memory environments to allow users to reduce cost. For example in Lambda the lowest setting is to have 128 MB of memory which also provides just a portion of a vCPU. Often users complain .NET is too slow at cold start for these types of environments and switch to languages like typescript which often has better cold start performance.

A common scenario would be a Lambda or Azure function listening to events from S3 or Blob storage. They are most likely going to use the respective cloud provider SDK to handle access to the object and possibly due some manipulation. Since best practice for Lambda and Azure functions is right them for a single purpose as part of a micro services architecture they are possibly only using a few operations of the SDK. For the AWS SDK the combination of the core package and s3 package is 2 megs itself but for function just doing a get and put I would expect only about 5 or 10 percent of the SDK's code is used. Granted I recognize the AWS SDK needs to be updated to support trimmable to get this benefit.

My scenario has been all focused on AWS Lambda and Azure functions but adding trimming for regular fx-dependent apps should also help startup times for container based applications running in constraint CPU/Memory environments.

**Comment by agocke** [comment]
I'm not sure I follow the reasoning here. Given that the scale of the dotnet framework itself is tens to hundreds of MB, how is trimming a third-party SDK which is on the order 5-10 MB going to help? Cold start, for example, heavily depends on how much code is JITed during startup, the vast majority of which will be in the framework, not the user's app.

I think we need some hard data to move forward here. Since trimming should work the same in an FX-dependent scenario, it would be good to build a representative sample app as a self-contained app and trim it, then see what the resulting savings are for the non-framework assemblies. Then we can see exactly what the benefit would be.

**Comment by jkotas** [comment]
> As for this specific scenario, it seems it's mostly driven by startup performance (please correct me if I'm wrong). I would not expect there to be a meaningful difference in startup between trimmed and untrimmed framework dependent application. 

The specific scenarios that @normj highlighted are serverless environments like AWS Lambda and Azure Functions. The startup time for these scenarios is `<time to download the app from storage to the executing machine>` + `<time to start the process>`. Trimming reduces the first component. Savings depend on the download speed from storage to the executing machine. I agree that it would be useful to get some absolute numbers, so we have a better idea how much this saves.

The runtime cost is typically amortized among the many different functions/lambdas executing on the same physical machine, so one is not really paying for download cost of the runtime itself.

**Comment by vitek-karas** [comment]
Thanks @jkotas - it wasn't clear to me if the "download the app" is part of the startup cost or not. In that case I can see that trimming might help, question is by how much.

**Comment by normj** [comment]
Sorry I got swamped and haven't been able to respond back to this sooner.

@jkotas is right that part of the startup case in serverless environments is preparing the environment which involves downloading.

@vitek-karas That is interesting your suggesting of using trimmed assembles from a self contained publish and copying them over into a framework dependent app. I'll see if I can make that work.

**Comment by PJB3005** [comment]
A simple example I can give for why you want to trim framework-dependent applications: large libraries like `TerraFX` are *designed* to be trimmed due to their size. `TerraFX.Interop.Windows.dll` is **16 MB** untrimmed. In our case (we can't use self contained) this basically saves like 10% of our program's size (and I haven't even bothered to apply trimming for anything else yet, still a lot to save).

**Comment by binginsin** [comment]
Are there any updates on this? Should this issue be moved / recreated in the dotnet runtime project?

**Comment by agocke** [comment]
We have no plans to do this any time soon. I will close this as not planned.
