### ISSUE TITLE
THIRD-PARTY-NOTICES.TXT needed for linker repo?

### ISSUE THREAD

**Issue by leecow** [dotnet/linker#2706]
If third-party components are used in a .NET repo, a THIRD-PARTY-NOTICES.TXT detailing any third-party source code included in final built artifacts, along with the controlling license information must be included and maintained at the root of the affected repo ([dotnet/runtime example](https://github.com/dotnet/runtime/blob/main/THIRD-PARTY-NOTICES.TXT)). 

During product build, these files are used to create a unified TPN file and included in the final installer builds ([example](https://github.com/dotnet/runtime/blob/main/src/installer/pkg/THIRD-PARTY-NOTICES.TXT)) and source-build offerings. 

Some repos will not need this notice as no third-party code is included in the final build artifacts.

Tracking issue: https://github.com/dotnet/runtime/issues/61466

**Comment by tlakollo** [comment]
This is possibly related to https://github.com/dotnet/linker/pull/2469, this PR addresses the THIRD-PARTY-NOTICES file along with other problems with licenses but needs special review due to CELA requirements
cc @richlander

**Comment by leecow** [comment]
Perfect,  looks like this will get added once that PR is complete.
