### ISSUE TITLE
Track FlowCapture of properties in analyzer

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#2729]
One of the issues encountered in https://github.com/dotnet/linker/issues/2718 is a NotImplementedException for an assignment to a FlowCaptureReference. Here is an example of code that produces this pattern:
https://github.com/dotnet/aspnetcore/blob/61506cd77e9f2c457afb27e487789585bea90264/src/JSInterop/Microsoft.JSInterop/src/DotNetStreamReference.cs#L18

As I understand it, flow captures are references to values created in one part of the CFG, so that they can be used from other parts of the CFG. For example, the null-coalescing pattern `local = GetA() ?? GetB()` translates into something like the following CFG:

- Basic block 1:
  - Operation: FlowCapture-1 captures the result of `GetA()`
  - BranchValue: IsNull(FlowCapture-1)
- Basic block 2 (reached from 1 when IsNull returns false)
  - Operation: FlowCapture-2 captures FlowCaptureReference to FlowCapture-1
- Basic block 3 (reached from 1 when IsNull returns true)
  - Operation: FlowCapture-2 captures result of `GetB()`
- Basic block 4: reached from 2 and 3
  - Operation: assigns (FlowCaptureReference to FlowCapture-2) to `local`.

So here FlowCapture-1 is used track the result of `GetA()` which is used from different branches in the CFG.

This is already handled in the analyzer for the most part. The problem occurs for some assignments to properties. The CFG is something like this:
- Basic block 1:
  - Operation: FlowCapture-1 captures a PropertyReference to Property
- ... (produce a FlowCapture-2 which stores the result of the null-coalescing operation)
- Basic block n:
  - Operation: assigns (FlowCaptureReference to FlowCapture-2) to (FlowCaptureReference to FlowCapture-1)
    - This represents the property assignment as an assignment through a flow capture reference - the case we don't handle.

To fix this I think the analyzer will need to introduce a new dataflow value to track the PropertyReference, up until the point where it is used for the assignment. I think in general the same captured PropertyReference could be used for reads and writes, for example:
`Property ??= (GetA() ?? GetB())`. Here the property needs to be read and written.

Opening this for discussion in case others have ideas about different ways to handle this. /cc @agocke @vitek-karas

**Comment by agocke** [comment]
I'm not sure I follow -- in this example, doesn't FlowCapture basically mean "temporary variable"? And doesn't FlowCaptureReference mean reference to temporary variable? So assigning to a FlowCaptureReference seems like it should be an assignment to the temp, but you seem to be describing an assignment to the property.

**Comment by sbomer** [comment]
> doesn't FlowCapture basically mean "temporary variable"?

That was my mental model up until now - glad to hear that this is an ok way to think about it. But in this example it looked to me like the assignment to the FlowCaptureReference was representing a property assignment, leading me to think that FlowCaptures aren't exactly what I thought.

Or maybe I missed something. I will take another look at the CFG and double-check that it doesn't later assign the FlowCapture to the property in a separate operation.

**Comment by agocke** [comment]
No, I think you're right. I created a test and this was the last stmt:

```
++>         Block[B6] - Block
++>             Predecessors: [B4] [B5]
++>             Statements (1)
++>                 ISimpleAssignmentOperation (OperationKind.SimpleAssignment, Type: System.String, IsImplicit) (Syntax: 'Prop ??= (G ...  ?? GetB())')
++>                   Left:
++>                     IFlowCaptureReferenceOperation: 0 (OperationKind.FlowCaptureReference, Type: System.String?, IsImplicit) (Syntax: 'Prop')
++>                   Right:
++>                     IFlowCaptureReferenceOperation: 3 (OperationKind.FlowCaptureReference, Type: System.String, IsImplicit) (Syntax: 'GetA() ?? GetB()')
```

**Comment by agocke** [comment]
I agree, this is surprising to me, as this basically implies that a flow capture reference can be doubly indirect, namely that it can point back to a property. I'll ask Roslyn for clarification

**Comment by agocke** [comment]
OK, sounds like this is intentional, and the intent is that the underlying property reference is the thing that is being captured, so it's effectively an assignment to the underlying property.

In that case, it seems like we can treat this as an alias to the underlying property reference, no?

**Comment by sbomer** [comment]
Thanks for looking into it!
> it seems like we can treat this as an alias to the underlying property reference

Agreed, that sounds like what I was suggesting (introduce a new value that tracks the underlying property reference) and I think it should work.

**Comment by agocke** [comment]
Maybe it could be simpler -- don't even track the property via value at all? What if we just treat it as an assignment to the property, i.e. make the node transparent for all intents and purposes.

**Comment by sbomer** [comment]
I think the problem is that at the point of the assignment, all we have for the LHS is an IFlowCaptureReference - so it seems like we need to remember for a given flow capture, that it references a property (and which particular property) - hence the extra dataflow value. Or is there a way to tell at the point of the assignment without tracking anything?

**Comment by agocke** [comment]
I assume the CaptureId is unique to the graph, so we could simply keep a static list of captured nodes. We're still "tracking" extra data, but maybe it's cheaper because it doesn't change based on the flow?

**Comment by sbomer** [comment]
Got it, yeah that could work.

**Comment by sbomer** [comment]
It seemed like it was easiest to just pass it through with the dataflow state, but as a separate dictionary so that it doesn't participate in the ValueSet meet semantics - see https://github.com/dotnet/linker/pull/2730 for the initial approach.

**Comment by agocke** [comment]
Makes sense -- my advice was aimed at simplifying implementation, so if it's easier to just add a new node, that seems good.

**Comment by vitek-karas** [comment]
I didn't try this, but I think introducing a PropertyValue into the value system (derived from SingleValue) makes a lot of sense. We already have a FieldValue which can appear on both left and right side of assignments - the PropertyValue would effectively operate the same way.
This could be analyzer specific - the value would not be used by linker at all. We just need to make sure that before it's passed to the shared code it's translated into a method call to either the setter or getter as appropriate.
That way we would not need a new state dictionary, since the current local state already handles captured values. The meet semantics is "concatenate" for values, which is not exactly the right one, but if roslyn makes sense, then it should not use the same capture ID for more than one property, and thus we should only ever get one value for it in the local state. And even if we don't, the system should work just fine, we simply iterate over the values as we do with everything else.
