### ISSUE TITLE
Descriptor marking entire assembly doesn't seem to mark exported types

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/linker#2776]
It seems that adding a descriptor like
```XML
<linker>
   <assembly fullname="System.Runtime"/>
</linker>
```

Doesn't actually preserve all type forwarders on the assembly. But passing `TrimmerRootAssembly Include="System.Runtime"` works...

**Comment by agocke** [comment]
Closing as TrimmerRootAssembly is the path forward.
