### ISSUE TITLE
Since, ILMerge is archived does this project offer static linking?

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/linker#2870]
As the title asks! Since, the ILMerge project has been archived and no longer maintained, does this mean that this project carry forward the static linking feature? If so, I can't see any documentation of that. If it's not, then is there a plan to provide static linking?

**Comment by vitek-karas** [comment]
What do you mean by "static linking"?

I think ILMerge provided a way to produce one assembly out of many assemblies. The linker doesn't do that (and there are no plans to add that functionality).

If you're looking for a way to have fewer files in your application then you can use single-file publish: https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview

There are also non-Microsoft tools which can do what ILMerge did, or similar. I think Fody can do something similar.

**Comment by Nirmal4G** [comment]
> What do you mean by "static linking"?

ILMerge's project description says static linking of assemblies. So, I thought that was the terminology for merging assemblies in the .NET World.

> ...you can use single-file publish...

Yeah, I knew about that but I'm not a fan of that implementation. Seems incomplete as it extracts to a temp folder and uses it. If we have a similar usecase, I don't mind extracting it to a local file system temporarily but cleaning up afterwards is always a problem. So, no, I don't quite like this one.

But my scenario is for merging assemblies and distributing MSBuild tasks as a standalone package. Few of the official packages use ILMerge to merge multiple assemblies after trimming the unnecessary code-paths but when I started to look into ILMerge, it's already archived. So, I thought it would become this project. But this project only does trim and it's quite good too! Me Like!!! But if this provides merging of assemblies, I would be able to ship standalone MSBuild tasks without any additional files.

**Comment by vitek-karas** [comment]
> Single-file:  Seems incomplete as it extracts to a temp folder and uses it.

That was only true for .NET Core 3.1. In .NET 6 the default single-file bundles all managed dependencies into the executable and runs them from the executable directly - it doesn't write anything to disk. More details: https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md

**Comment by Nirmal4G** [comment]
Nice, running through it, seems like there are gotchas but definitely a step in the right direction. Design says Host is customizable, YAY for open source. But this doesn't solve for non-executables like assemblies.

> Tools like ILMerge combine the IL from many assemblies into one, but lose assembly identity in the process. This is not a goal for single-file feature.

I remember there is a `netmodule` concept in .NET Framework (_used to compile multi-language [C#, VB, F#] .NET sources into single assembly!?_). While I don't know much about it, could it provide the identity that the ILMerge removes? Also, does .NET Core still support this concept?

**Comment by Nirmal4G** [comment]
Seems like that could be the solution for a **single-file assembly** feature similar to single-file executable! If that is not supported in .NET Core, **where can I create a feature request?** Also, is the multi-module assembly feature explicitly dropped like AppDomains and SystemWeb or is it just not implemented because of resources?

**Comment by Nirmal4G** [comment]
My scenario is the same as using ILMerge. Currently `NuGet.Build.Tasks.Pack` uses it to do what I've described!

Pinging
@zivkan as `NuGet.Build.Tasks.Pack` uses ILMerge to make Pack tasks portable.
@dsplaisted Does the SDK tasks use ILMerge or any other tool to merge assemblies or do we leave it alone?
@rainersigwald Can we create a truly portable tasks library and load it across MSBuild versions? Is it possible with a custom TaskHost that takes care of MSBuild lib refs or we bring our own (_something similar to a AppHost in .NET Core_)?

**Comment by dsplaisted** [comment]
No, we don't use ILMerge or anything like it in the .NET SDK.

**Comment by MichalStrehovsky** [comment]
Netmodules (or multi-module assemblies) will not be supported by the runtime. See e.g. https://github.com/dotnet/runtime/issues/10598 for the reasoning.

That said, you could use multi-module assemblies in your build steps and if everything is linked into a single assembly by the time the runtime sees it, it's all good. The workflow is basically:

```
echo class Foo { } > foo.cs
echo class Program { static void Main() { new Foo(); } } > program.cs
csc /target:netmodule foo.cs
csc program.cs /addmodule:foo.netmodule /target:module
link program.netmodule foo.netmodule /out:program.exe /entry:Program.Main /subsystem:console
```

The above produces program.exe that has both the class Foo and Program in the single assembly.

One would need to map this into MSBuild project files somehow. I don't think there's first class support.

`link` on the last line is link.exe from the VC++ SDK - it can statically link .NET code in the real meaning of the term link, not as the overload of the term used in this repo (that has very little to do with linking). It obviously only works on Windows though.

Basides Fody, I've also seen people embedding their dependent assemblies as managed resources, hooking the `AppDomain.AssemblyResolve` event and doing `Assembly.LoadFrom` with bytes obtained from the embedded assemblies using `GetManifestResourceStream` as a response to the event.

**Comment by agocke** [comment]
Closing as resolved

**Comment by Nirmal4G** [comment]
@MichalStrehovsky What about linking into another Assembly instead of an executable. Will the above steps work for the same?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky What about linking into another Assembly instead of an executable. Will the above steps work for the same?

It will work the same for libraries.
