### ISSUE TITLE
Address StaticCs.0.1.0 source-build prebuilt

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/linker#2902]
StaticCs.0.1.0 is being detected as a source-build prebuilt.  This needs to be addressed before 7.0 can be released.  [StaticCs](https://github.com/agocke/static-cs) either needs to be conditioned out so that it is not referenced in source-build or it needs to be included in source-build.  See the [source-build guidance for adding new dependencies](https://github.com/dotnet/source-build/blob/main/Documentation/sourcebuild-in-repos/new-dependencies.md) for additional details.

cc @agocke

**Comment by agocke** [comment]
@MichaelSimons Thanks. I own this package and it contains an analyzer and source files that are included into the target package.

Would you recommend excluding it, or use something like the text-only packaging process?

**Comment by MichaelSimons** [comment]
If the package contains and analyzer, if can't be handled as a text-only package.  I am ignorant on the usage of the ILLink.RoslynAnalyzer.  I see it ships as part of the SDK.  I presume source-build customers would want this functionality.  Is that correct?

**Comment by agocke** [comment]
Right, these projects are part of the linker and the associated analyzer, which ship with the .NET SDK.

I think excluding the analyzer makes sense. One more question: what about static files in the NuGet package? In theory we should be able to include those without problems, right?
