### ISSUE TITLE
AD0001: Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.InvalidCastException'

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/linker#3106]
### Describe the bug

Annotating a parameter on a local function with `[DynamicallyAccessedMembers]` causes `ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer` to throw the following exception:

```
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.MethodSymbol' to type 'Microsoft.CodeAnalysis.ITypeSymbol'.'.
```

This was observed in https://github.com/dotnet/aspnetcore/pull/44925. The culprit was [this line](https://github.com/dotnet/aspnetcore/blob/45a75ad446294116024e640bb7efabfcfe2ac210/src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs#L132).

**SDK version with the bug:**
8.0.100-alpha.1.22556.1

**Last known SDK version without the bug:**
8.0.100-alpha.1.22531.1

### Steps to reproduce

1. Checkout https://github.com/dotnet/aspnetcore/tree/98bd1e8085ba090a352ed1eda7f86fd2bd5381ea
2. Build the solution following [these steps](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md)

### Expected behavior

The build completes successfully.

### Actual behavior

The build fails with the aforementioned error.

**Comment by JamesNK** [comment]
FYI this issue impacts the dotnet/aspnetcore repository and blocks us from updating the SDK. It's not urgent to update the SDK, but prompt progress would be appreciated.

**Comment by jtschuster** [comment]
The fix is checked in and flowing to sdk in https://github.com/dotnet/sdk/pull/29013

**Comment by jtschuster** [comment]
Closing since it looks like there's a separate issue holding up the ASP.Net PR
