### ISSUE TITLE
Error when building .NET7 macOS app

### ISSUE THREAD

**Issue by tipa** [dotnet/linker#3148]
I am trying to built a .NET7 macOS app using `dotnet publish -c Release`.
Throws this error:

```
  Optimizing assemblies for size. This process might take a while.
ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues [/Users/...]
  Fatal error in IL Linker
  Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
     at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
     at Mono.Linker.AnnotationStore.IsMarked(IMetadataTokenProvider provider)
     at Xamarin.Linker.BackingFieldDelayHandler.ReapplyDisposedFields(DerivedLinkContext context, String operation) in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/dotnet-linker/BackingFieldDelayHandler.cs:line 74
     at Xamarin.Linker.BackingFieldReintroductionSubStep.Initialize(LinkContext context) in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/dotnet-linker/BackingFieldDelayHandler.cs:line 102
     at Mono.Linker.Steps.SubStepsDispatcher.InitializeSubSteps(LinkContext context)
     at Mono.Linker.Steps.SubStepsDispatcher.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
/usr/local/share/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.ILLink.Tasks/build/Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/...]
```

Let me know if you need any additional info.

**Comment by vitek-karas** [comment]
@marek-safar could you please tag the owners of the Xamarin custom steps (macOS)?
The custom step is effectively calling `AnnotationStore.IsMarked(null)` which will crash the linker.

**Comment by rolfbjarne** [comment]
@tipa would it be possible get access to your project, or a test project we can use to reproduce this?

**Comment by tipa** [comment]
I was able to reproduce the problem by simply adding this piece of code to an otherwise empty app:
```
new NSView().HeightAnchor.ConstraintEqualTo(1);
```

Are you able to reproduce it? I can otherwise try to create a demo project.
The problem just started to appear recently. I am using .NET7 and the preview Xamarin SDKs (Xamarin.Mac Version: 9.0.0.27)

**Comment by rolfbjarne** [comment]
@tipa 

> @rolfbjarne I was able to reproduce the problem by simply adding this piece of code to an otherwise empty app:
> 
> ```
> new NSView().HeightAnchor.ConstraintEqualTo(1);
> ```
> 
> Are you able to reproduce it? I can otherwise try to create a demo project. The problem just started to appear recently. I am using .NET7 and the preview Xamarin SDKs (Xamarin.Mac Version: 9.0.0.27)

I tried `dotnet new macios` and then adding that line, but that works fine.

Could you try to create a repro project and also get a [binary build log](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) from a failing build? The log will show the exact versions you're using, which should make sure I'm testing the same thing you're using.

**Comment by rolfbjarne** [comment]
I can reproduce now.

For a workaround, reference the NSAnchorLayout.Item property:

```cs
var anchor = new NSView().HeightAnchor;
anchor.ConstraintEqualTo(1);
var item = anchor.Item; // prevents the problem
```

**Comment by tipa** [comment]
Thanks for the workaround. Unfortunately it's not really an option for me to use it as I am using this method call several hundred times in each of my apps. Hope it will get resolved in one of the next .NET7 service releases :)

**Comment by rolfbjarne** [comment]
You only need to access NSAnchorLayout.Item once anywhere in your app (in a way that the linker doesn't remove the field).

**Comment by tipa** [comment]
Looks like this has been closed and fixed [here](https://github.com/xamarin/xamarin-macios/issues/16957), correct?

**Comment by rolfbjarne** [comment]
Yes, this is fixed.
