### ISSUE TITLE
Add members accessible due ComVisibleAttribute handling

### ISSUE THREAD

**Issue by ericstj** [dotnet/linker#378]
See https://github.com/dotnet/corefx/pull/32491

The linker was trimming an internal interface because it didn't see any uses, but it would be used by COM.  The managed code passes the object implementing that interface to native code and the native code would QI for the interface.  Runtime would return the CCW for the interface but that would be missing the necessary methods and native code AV'ed when calling it.

We should look at a heuristic for identifying these interfaces.

@jkotas suggests looking at the ComImportAttribute: I'm not sure that's sufficient.  I think technically any COMVisible interface would fall in this bucket.  I believe most interfaces are COMVisible by default, but @luqunl would know better here.

/cc @sbomer @erozenfeld

**Comment by ericstj** [comment]
I see, thanks for that clarification.

**Comment by erozenfeld** [comment]
This is the same issue we encountered in dotnet/corefx#30092 where System.Drawing.Common.Interop/Ole32/IStream (https://github.com/dotnet/corefx/blob/dee434428ee392302ff2050bbee304c9fce68b2f/src/Common/src/Interop/Windows/Ole32/Interop.IStream.cs#L22), which is also [ComImport] had its members trimmed. I opened #338 to track fixing that in the linker but it looks like my fix suggestion there wasn't correct. I'll close that issue and keep this one open.

**Comment by erozenfeld** [comment]
>> For ComVisible case, members in all public types should not be trimmed --- I guess ILLinker doesn't trim public types' members.

ILLink doesn't trim public type members when running with -r option. That's how it's running in corefx. However, it does trim public type members in other configurations. The fix for this issue should include not trimming members in [ComVisible] public types.

**Comment by luqunl** [comment]
> The fix for this issue should include not trimming members in [ComVisible] public types.

Yes, Please. CCW scenario need these type members.

**Comment by vitek-karas** [comment]
In .NET 7 the built-in COM is not trim compatible (and probably never will be, it's almost impossible to guarantee correctness statically). So it's disable by default. The recommended solution for making COM usage trimmable is to use [ComWrappers](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-comwrappers?source=recommendations). COM through ComWrappers is completely trimmable and supported.
