### ISSUE TITLE
Investigate roslyn APIs instead of CodeDOM for tests compilation

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#499]
This issue tracks figuring out the best variety of roslyn to use for running tests:
- in-process with Roslyn APIs vs out-of-process via csc.dll
- likely turning on server GC for roslyn if we see an improvement

From @mrvoorhe in https://github.com/mono/linker/pull/489#discussion_r266877076:

> 
> I wonder if it would be simpler to just run the compiler out of process regardless of NETCOREAPP? Do you know what the performance difference is between in process and out of process?
> 
> We actually override these compile methods and route them through our own helpers that run either mcs or csc out of process. In our case the motivation is that for a majority of the tests, we just want to use the fastest available compiler on the current platform . Roslyn w/ server mode is the fastest, but we used to have some build machines that were older versions of macOS which didn't support netcore2.0 so we would fallback to mcs.
> 
> If we adopt all out of process here the logic becomes
> 
>     Find the fastest compiler available.
>     Build up command line arguments
>     Run.
> 
> It seems like that would be more straight forward and involve fewer if defs and less code.
> 
> On the subject of Roslyn server mode. Will this approach utilize server mode? We found that roslyn is painfully slow without server mode. It would be nice to leverage server mode.
>

**Comment by vitek-karas** [comment]
I think this has been done, the tests are currently compiler using Roslyn in-proc.
