### ISSUE TITLE
[Preserve (Conditional=true)] does not really (conditionally) work on fields

### ISSUE THREAD

**Issue by spouliot** [dotnet/linker#516]
https://github.com/mono/linker/blob/327e73f0830ae6cfe377dbbc761ba6000a9ea934/src/tuner/Mono.Tuner/ApplyPreserveAttributeBase.cs#L95

I run into this again. Took me a while to realize it's the same issue I filed  6+ years ago (Mar 2, 2013 at 1:13 PM) as a low priority enhancement in our (old) Trello boards [1].

> To avoid crashes this is implemented as an unconditional preserve.
> The only case where monotouch used this has been workaround in maccore b6005955a98bf0e42076bb77adf3ce10bde067ac
> Fix this properly (low priority IMO) requires duplicating the Method-related code to conditional preservation.

[1] https://trello.com/c/GwUYFyCV/102-preserveconditionaltrue-does-not-work-on-fields <- for historical value only :)

**Comment by vitek-karas** [comment]
`illink` doesn't recognize `PreserveAttribute` anymore.
