### ISSUE TITLE
Inconsistent assembly resolution via -x and -a

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/linker#56]
The assemblies provided via `-a` argument and within the xml file provided via `-x` are  processed differently: 

1) `-a`: Accepts arguments of the form `file.exe` directly reads the file if it exists. 
           It also accepts just `file` and resolves the name as an assembly.
           https://github.com/mono/linker/blame/master/linker/Mono.Linker/LinkContext.cs#L159-L168
2) `-x`: Does not accept `files.exe` form, just assembly names.

Processing the argument of `-a` in two ways causes confusion, and results in some assemblies being processed twice with different names.

For example: 
`monolinker -a reflect.exe -x reflect.xml`

Silently produces undesirable effect by 
- processing the reflect.exe assembly twice and 
- creating duplicate TypeDefinitions for all the types referenced in reflect.xml
This effectively nullifies reflect.xml file and causes unexpected output.

Some possible fixes are:
1) Strip the extensions from `-a` arguments effectively causing (2) in this case
2) Always have  `LinkContext::Resolve` resolve by name and not FileName

**Comment by vitek-karas** [comment]
We've probably changed the command line, but `-x` in `illink` adds a new descriptor XML file. It has to be a valid file path. And it doesn't make sense to support just "assembly name" as there would be no way to resolve it to a file path (unlike assemblies).
