### ISSUE TITLE
Single Linker config for .NET Native and Mono

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/linker#57]
I fully support the idea of a linker in .NET Core but please consolidate the linker directives. There's rd.xml for .NET Native and this new thing. Please pick one and use it for both toolchains. Otherwise we'll need to duplicate linker directives and that's going to lead to errors.

**Comment by hrumhurum** [comment]
Please strongly consider to consolidate the formats.

Just hit a project where a set of .NET Standard libraries were both used in Xamarin and UWP hosts. UWP was a breathe thanks to RD.XML and its ability to be _embedded_ right in the library.

Xamarin experience was considerable worse as I had to specify the same rules, but this time at a central location which is a linker description file. Did not like it at all, especially given the fact that some .NET Standard libraries are authored by another teams and its their responsibility to make it linker friendly, not mine.

RD.XML format support in linker is highly welcome. This would eliminate the sharp edges and unpleasant dichotomy we currently have. Especially given the fact that .NET Linker now targets .NET Core.

**Comment by vitek-karas** [comment]
The plan is to teach NativeAOT about the linker format - it actually already does some of this, main part of the missing work is tracked here: https://github.com/dotnet/runtime/issues/73083

Going forward the recommendation for libraries/apps is to not use the XML files but instead use code. So either (in recommendation priority order):
* direct references
* use source generators to produce direct references
* annotated reflection code with `DynamicallyAccessedMembersAttribute`
* use `DynamicDependencyAttribute` (this is basically a code replacement for the descriptor XML file)
