### ISSUE TITLE
"Modes" for illink

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#624]
The ILLink defaults in .NET Core 3.0 are to root non-framework assemblies, and keep used framework assemblies entirely. This default was motivated by a desire to keep the template apps working with the linker out of the box.

From https://github.com/dotnet/sdk/pull/3279/files#r289192515:

> The currently-supported ways to override defaults are:
> 
> - adding roots via TrimmerRootDescriptor and TrimmerRootAssembly, which doesn't make it any more useful for portable apps, and
> - using ILLink task directly, explicitly specifying the set of roots.
> 
> Somebody could do what the tests do and remove items from the defaults, but it requires depending on a private target.
> 
> In the future we may consider supporting something like IsTrimmable on PackageReferences, but until then I think we should keep the error - I can't think of a reasonable condition to put it under with the current override mechanisms. And someone who is willing to use the task directly will likely be able to work around the error as well.

> I also wanted to note more generally about overriding defaults - the out of band package had more high-level msbuild properties that mapped to different combinations of roots and linker actions. However it ended up with a bunch of logic in msbuild that wasn't tested and kept breaking. If we do introduce a high-level "mode" concept, we'll need to ensure test coverage of different modes, and probably make this concept known to illink itself.

The current defaults map to the following command-line options:
`-c copyused -u copyused [-p copy <non-fx assemblies>] [-a <non-fx assemblies>]`.

We would like to provide an easy way to choose different linker "modes" for different scenarios. Some interesting modes we may want to support:
- an aggressive mode that roots the entry point and trims unused IL
- a partial crossgen mode that roots the entry point (or maybe non-framework types?) and passes hints to crossgen that cause it to skip AOT compilation of unused code, but keeps IL for everything

For example, here are some combinations of settings I've tested with in the past:
```xml
<!-- trim: root/copy non-fx, and link fx. -->
<PropertyGroup Condition=" '$(linkermode)' == 'trim' ">
  <_ExtraTrimmerArgs>-c link -u link</_ExtraTrimmerArgs>
</PropertyGroup>
<ItemGroup Condition=" '$(linkermode)' == 'trim' ">
  <TrimmerRootAssembly Include="@(_ManagedAssembliesToLink)" Condition=" '%(_ManagedAssembliesToLink.IsTrimmable)' != 'true' " />
  <_ManagedAssembliesToLink Update="@(_ManagedAssembliesToLink)" Condition=" '%(_ManagedAssembliesToLink.IsTrimmable)' != 'true' ">
    <action>copy</action>
  </_ManagedAssembliesToLink>
</ItemGroup>


<!-- assemblytrim: root/copy non-fx, and copy used fx. -->
<PropertyGroup Condition=" '$(linkermode)' == 'assemblytrim' ">
  <_ExtraTrimmerArgs>-c copyused -u copyused</_ExtraTrimmerArgs>
</PropertyGroup>
<ItemGroup Condition=" '$(linkermode)' == 'assemblytrim' ">
  <TrimmerRootAssembly Include="@(_ManagedAssembliesToLink)" Condition=" '%(_ManagedAssembliesToLink.IsTrimmable)' != 'true' " />
  <_ManagedAssembliesToLink Update="@(_ManagedAssembliesToLink)" Condition=" '%(_ManagedAssembliesToLink.IsTrimmable)' != 'true' ">
    <action>copy</action>
  </_ManagedAssembliesToLink>
</ItemGroup>


<!-- hintentry: root entry point, addbypassngen to everything. -->
<PropertyGroup Condition=" '$(linkermode)' == 'hintentry' ">
  <_ExtraTrimmerArgs>-c addbypassngen -u addbypassngen</_ExtraTrimmerArgs>
</PropertyGroup>
<ItemGroup Condition=" '$(linkermode)' == 'hintentry' ">
    <TrimmerRootAssembly Include="@(IntermediateAssembly->'%(FileName)')" />
    <_ManagedAssembliesToLink Update="@(IntermediateAssembly)">
      <action>addbypassngen</action>
    </_ManagedAssembliesToLink>
  <_ManagedAssembliesToLink Update="@(_ManagedAssembliesToLink)" Condition=" '%(_ManagedAssembliesToLink.IsTrimmable)' != 'true' ">
    <action>addbypassngen</action>
  </_ManagedAssembliesToLink>
</ItemGroup>


<!-- hintused: root non-fx, addbypassngen to non-fx, addbypassngenused to fx. -->
<PropertyGroup Condition=" '$(linkermode)' == 'hintused' ">
  <_ExtraTrimmerArgs>-c addbypassngenused -u addbypassngenused</_ExtraTrimmerArgs>
</PropertyGroup>
<ItemGroup Condition=" '$(linkermode)' == 'hintused' ">
  <TrimmerRootAssembly Include="@(_ManagedAssembliesToLink)" Condition=" '%(_ManagedAssembliesToLink.IsTrimmable)' != 'true' " />
  <_ManagedAssembliesToLink Update="@(_ManagedAssembliesToLink)" Condition=" '%(_ManagedAssembliesToLink.IsTrimmable)' != 'true' ">
    <action>addbypassngen</action>
  </_ManagedAssembliesToLink>
</ItemGroup>
```

However, as mentioned above, we may not want to maintain them in MSBuild. I would prefer to define a "mode" concept and have this map to the appropriate set of underlying options. To accomplish this, we would want to introduce a few new command-line options to illink that present the same functionality as existing options, but along a different axis. One challenge is that illink proper doesn't know which assemblies are framework assemblies on .NET Core. A quick suggestion we could iterate on:
- `--mode <modename>`: would imply values for `-u` and `-c`, and `-a` or `-r` (on the non-framework assemblies or the entry point)
- `--entry-point <assemblyname>`: tells the linker which assembly contains the entry point
- `--framework-assembly <path/to/assembly.dll>`: simply tells the linker that this is a framework assembly. The "core" action (specified via `-c` or implied by `--mode`) would apply to these assemblies if specified, instead of the currently-incorrect heuristic the linker uses to detect "core" assemblies.

@marek-safar do you think an approach similar to this is at all reasonable?

**Comment by marek-safar** [comment]
I need to think about this little bit more but I am certainly not against it. We have no way to express the core assemblies and I'd love to get that resolved. The way I am thinking is to add `-reference-core path` to indicate that.

Now to the linker modes. This is something that needs more thinking. You are starting way off on the conservative side so something that is the conservative default is for you aggressive linking so I am not sure we need to add that this way because that's what `-a` does by default

**Comment by sbomer** [comment]
I think we can call this done:
- We opted against a way to specify framework assemblies. Instead the `IsTrimmable` assembly metadata controls behavior per-assembly.
- The "mode" can be specified per-assembly via `--action`, or as a global default, with separate values for unattributed assemblies (`--action`) vs `IsTrimmable` assemblies (`--trim-mode`).
