### ISSUE TITLE
Add support for C++/CLI assemblies

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#676]
Currently the linker skips C++/CLI assemblies (see https://github.com/mono/linker/pull/658), because
1. it's not aware of native code in mixed-mode assemblies
2. even for /clr:pure assemblies, cecil may reorder IL data that C++/CLI expects to be preserved (see https://github.com/mono/linker/issues/651#issuecomment-510689413).

As a result, dependencies of the C++/CLI assemblies aren't analyzed, requiring workarounds like https://github.com/dotnet/wpf/pull/1387.

This issue tracks improving the linker's support for C++/CLI assemblies. There are a number of routes we could take:
- making the linker aware of native code (probably expensive)
- preserving the ordering of IL data (which would work for /clr:pure assemblies, and probably involves a cecil fix)
- letting the linker analyze assemblies without modifying them (see https://github.com/mono/linker/issues/639)

**Comment by MichalStrehovsky** [comment]
`/clr:pure` [is now deprecated](https://docs.microsoft.com/en-us/cpp/build/reference/clr-common-language-runtime-compilation?view=msvc-160) so there's little point in adding support for that.

The only way how illink would be able to process C++/CLI is if illink was an actual, real,  linker (accepting obj files as input).

The produced EXE/DLL doesn't have enough information for illink to safely touch anything in it (the *real* linker already computed various relative offsets and threw away the relocation information for them). The .NET metadata is in the middle of the executable (in the `.rdata` section). The `.text` section precedes it and `.data` section follows. If illink resizes the .NET metadata in any way, it's going to invalidate all relative offsets within the image that follow the .NET metadata blobs.

I don't see a path to success with this, unless we accept that the file cannot be touched and just append data to it (i.e. we would bloat the file, keeping a dead copy of the old .NET metadata, with the hope that it will allow us to make non-C++ assemblies smaller).

**Comment by sbomer** [comment]
> I don't see a path to success with this, unless we accept that the file cannot be touched and just append data to it

Agreed, I think the current plan is to never touch them for the reasons you pointed out, but still analyze them for dependencies (and I don't think we should try to append a metadata copy either). @mateoatr

**Comment by vitek-karas** [comment]
Linker now scans C++/CLI assemblies, but it will never modify them. C++/CLI assembly is either removed as a whole, or kept untouched.
