### ISSUE TITLE
PublishTrimmed=true causes exception from trying to load type from wrong assembly

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/linker#697]
After setting `PublishTrimmed=true`, I am getting the following exception:

```
System.TypeLoadException: Could not load type 'System.Collections.Immutable.ImmutableDictionary`2' from assembly 'System.Diagnostics.TextWriterTraceListener, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

It seems strange that it is looking for `ImmutableDictionary` in `System.Diagnostics.TextWriterTraceListener` when it should be loading it from `System.Collections.Immutable`.

**Steps to reproduce**
1. Starting configuration: Win 10 machine with Docker and .NET Core SDK 3.0.100-preview7-012821 installed
1. `git clone https://github.com/dotnet/docker-tools.git`
1. `cd docker-tools`
1. `git checkout 0034133bf2214492c2949e7bd31bf22a85ab1856`
1. `cd Microsoft.DotNet.ImageBuilder\`
1. dotnet publish -r win-x64 -o c:\out
1. `git clone https://github.com/dotnet/dotnet-docker.git`
1. `cd dotnet-docker`
1. `c:\out\Microsoft.DotNet.ImageBuilder.exe showImageStats`

**Actual Results:**

```
System.TypeLoadException: Could not load type 'System.Collections.Immutable.ImmutableDictionary`2' from assembly 'System.Diagnostics.TextWriterTraceListener, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.DotNet.ImageBuilder.ViewModel.PlatformInfo.InitializeBuildArgs()
   at Microsoft.DotNet.ImageBuilder.ViewModel.PlatformInfo.Initialize(IEnumerable`1 internalRepos, String registry)
   at Microsoft.DotNet.ImageBuilder.ViewModel.ManifestInfo.Create(String manifestPath, ManifestFilter manifestFilter, IManifestOptionsInfo options)
   at Microsoft.DotNet.ImageBuilder.ViewModel.ManifestInfo.Load(IManifestOptionsInfo options)
   at Microsoft.DotNet.ImageBuilder.Commands.ManifestCommand`1.LoadManifest()
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args)
```

**Expected Results:**

1. The application should run without issue.  There should be no need to add any `TrimmerRootAssembly` properties because reflection is not used in this code path.
1. The exception message is confusing IMO.  Why is it trying to load `ImmutableDictionary` from 
`System.Diagnostics.TextWriterTraceListener`?

**Observations:**
1. Everything works as expected is you set `PublishTrimmed=false`
1. Prior to using `PublishTrimmed=true`, this project was using the ILLink NuGet package and everything was working correctly.
1. Adding a `TrimmerRootAssembly` will resolve this issue.
```
<ItemGroup>
  <TrimmerRootAssembly Include="System.Collections.Immutable" />
</ItemGroup>
```

**Comment by vitek-karas** [comment]
I didn't try the repro, but in .NET 6/7 the publish should either produce a warning or the app should work. If there's a different behavior observed please feel free to reopen the issue.
