### ISSUE TITLE
Third-party (DevExpress) DLLs not being trimmed

### ISSUE THREAD

**Issue by EatonZ** [dotnet/linker#772]
When using the **PublishTrimmed** setting on a .NET Core 3.0 WinForms project, combined with the **DevExpress.WindowsDesktop.Win** NuGet package, the entirety of that package gets bundled with the app, despite the **PublishTrimmed** setting. That is around 150 MB, most of which probably is not required at all.

DevExpress is aware of the problem and has determined that any fixes will need to go into .NET Core/linker. I hope you will consider improving the trimming feature in the near future, as huge WinForms apps are not particularly enticing right now.

[DevExpress ticket for reference](https://www.devexpress.com/Support/Center/Question/Details/T818991/net-core-3-0-massive-exe)

**Comment by marek-safar** [comment]
Could you please attach or link the project which reproduces this behaviour?

**Comment by EatonZ** [comment]
Hi @marek-safar, please see the latest comment from DevExpress [here](https://www.devexpress.com/Support/Center/Question/Details/T818991/net-core-3-0-massive-exe) (very bottom).

**Comment by zezba9000** [comment]
Are you using: <PublishReadyToRun>true</PublishReadyToRun>
That can make the result larger.

**Comment by EatonZ** [comment]
@zezba9000 Yup - I know about that setting, and that it does indeed increase sizes further. It's not quite related to this issue since this is about DLLs not being trimmed / unnecessary ones being included.

@marek-safar Let me know if you need anything else that may help.

**Comment by SimonCropp** [comment]
a repro using newtonsoft

new console app:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>
</Project>
```

no code in the program.cs

```
dotnet publish
```

Newtonsoft.Json.dll is still in the publish dir

**Comment by EatonZ** [comment]
Hi! With .NET 5 development well underway, what can be expected on this front?

**Comment by SimonCropp** [comment]
@marek-safar should this still have the "needs more info" label?

**Comment by marek-safar** [comment]
DevExpress libraries will most likely have to be validated for .NET5 to see if they are using any linker incompatible APIs

**Comment by SimonCropp** [comment]
@marek-safar shouldnt a consumer be allowed to opt in to trim any dlls they want?

**Comment by marek-safar** [comment]
They will most likely be able to do that in .net 5 as well

**Comment by vitek-karas** [comment]
This has been improved in .NET 6+. See the available options here: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options
