### ISSUE TITLE
Linker isn't removing references to WPF from a WinForms app

### ISSUE THREAD

**Issue by sbomer** [dotnet/linker#832]
As mentioned in https://github.com/dotnet/winforms/issues/2426, the self-contained publish output of a WinForms app will include WPF assemblies.

If this issue isn't solved on the SDK/winforms side, we should consider whether the linker can help trim those unused references. The sample shared in that issue has a publish profile with `PublishTrimmed` but the WPF assemblies were still kept - which makes sense given that the 3.0 defaults for the linker keep everything outside of netcoreapp.

If that gets solved on the SDK side, we can probably just close this.

**Comment by vitek-karas** [comment]
I think it's better to track this on the winforms side: https://github.com/dotnet/winforms/issues/3723
If there's a specific ask on linker as part of the bigger solution, then it should be created as a separate issue.
