### ISSUE TITLE
PublishTrimmed alter the mscorelib.dll cause app crash

### ISSUE THREAD

**Issue by John0King** [dotnet/linker#895]
```txt
Unhandled exception. System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.IsCopyConstructed' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```
![image](https://user-images.githubusercontent.com/13639146/71641703-3234c300-2cdb-11ea-90cb-447e1125f310.png)

**Comment by vitek-karas** [comment]
If this is still a problem in .NET 6+, please:
* Reopen this issue
* Make sure the app doesn't produce any warnings when published with trimming
* Ideally provide a smaller repro, or some additional information about the problem
