### ISSUE TITLE
Improve corlib linker descriptor

### ISSUE THREAD

**Issue by vargaz** [dotnet/linker#931]
It might be better/faster to implement this using attributes, to avoid the parsing of an xml file, the lookups,
   etc.
The precision of the linker descriptors is not good enough:
- for classes, it doesn't specify whenever the runtime can create instances of the preserved type.
   This means that virtual methods of the type cannot be removed.
- For preserve="fields", it doesn't specify whenever the field type needs to be preserved or just
  the field for layout purposes. It retains static fields as well.

These problems cause ref.emit classes to be retained even through the rest of the BCL only has a
reference to TypeBuilderInstantiation.

**Comment by marek-safar** [comment]
Totally agree that linker XML descriptors should not be used anywhere in BCL.

**Comment by vitek-karas** [comment]
AFAIK we've removed lot of them during .NET 6. @vargaz if this is still an issue, could you either provide specific examples? And even then the issue probably belongs to the runtime repo (At least at first).

**Comment by vargaz** [comment]
Can be closed i think.
