### ISSUE TITLE
[ComImport] Interfaces should have unused methods replaced with placeholders, not removed

### ISSUE THREAD

**Issue by Zhentar** [dotnet/linker#936]
When the linker detects that a ComImport method is not being used, it removes them from the interface. This is not correct: all ComImport interface methods are implicitly used, because they are used to determine the native vtable layout.

When Roslyn embeds interface definitions from interop dlls, it replaces unused member with void () placeholders: https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/Compilers/Core/Portable/MetadataReader/ModuleExtensions.cs#L193

Using a placeholder like that can unroot types used by the parameters/return values, so it can still help with further size reductions; but the methods cannot be removed entirely.

**Comment by vitek-karas** [comment]
There are no plans to support the so called "built-in" COM with trimming (it's basically impossible to statically prove its correctness). The recommended solution for COM with trimming is to use [ComWrappers](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-comwrappers?source=recommendations).
