### ISSUE TITLE
Add mapping from IL to source line / filename when logging warnings/errors

### ISSUE THREAD

**Issue by mateoatr** [dotnet/linker#987]
If we are to make the linker warnings and errors that we surface to IDEs actionable by the users, we need a way to get the source line and file name related to the piece of IL that made the illinker output a warning, this should be done by looking into the pdbs of the related dll/exe, since these contain a mapping between the IL and the declared symbols.

**Comment by vitek-karas** [comment]
This is implemented such that if linker can find the relevant PDBs, it will use it to read source/line info and report warnings with source/line. Otherwise it defaults to report warnings describing the metadata item they're associated with.
